Extrayendo tablas desde la base origen...

DimDate extraída: 350 filas
DimCustomerSegment extraída: 19 filas
DimProduct extraída: 25 filas
Error extrayendo FactSales: (psycopg2.errors.UndefinedTable) relation "FactSales" does not exist
LINE 1: SELECT * FROM "FactSales"
                      ^

[SQL: SELECT * FROM "FactSales"]
(Background on this error at: https://sqlalche.me/e/20/f405)

 Extracción finalizada.

Iniciando pipeline ETL...

Traceback (most recent call last):
  File "/home/alejandrito/Mydata/mydata/Python/Prueba_tecnina_SUDATA/prueba_tecnica/prueba_tecnica2/Ejercicio1/main.py", line 11, in <module>
    main()
  File "/home/alejandrito/Mydata/mydata/Python/Prueba_tecnina_SUDATA/prueba_tecnica/prueba_tecnica2/Ejercicio1/main.py", line 7, in main
    load_all(dataframes)
  File "/home/alejandrito/Mydata/mydata/Python/Prueba_tecnina_SUDATA/prueba_tecnica/prueba_tecnica2/Ejercicio1/load.py", line 26, in load_all
    upsert_from_df(engine, FactSales, dataframes["FactSales"], "Salesid")
                                      ~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'FactSales'
Extrayendo tablas desde la base origen...

DimDate extraída: 350 filas
DimCustomerSegment extraída: 19 filas
DimProduct extraída: 25 filas
FactSales extraída: 25 filas

 Extracción finalizada.

Iniciando pipeline ETL...


Pipeline ETL completado exitosamente.
